Only unmarshal json and map, code clean up, restrict log length of body
ONSdigital/dp-api-router pull request #123
Opened 2021-11-01 14:13 UTC by redhug1

### What

As per title

### How to review

Visual inspection.
Run tests ... with debugger, single stepping (add breakpoints) to observe that only files starting with { or [ are unmarshaled.

### Who can review

Anyone.

2021-11-01 16:07 UTC, daiLlew requested changes

2021-11-01 16:07 UTC, daiLlew commented on interceptor/interceptor.go
> +			if bodyLength > 30 {
Just curious - why is 30 the magic number?

2021-11-01 16:07 UTC, daiLlew commented on interceptor/interceptor.go
> +
I would recommend using the existing function for this - https://pkg.go.dev/encoding/json#Valid - why reinvent the wheel.

2021-11-01 16:13 UTC, daiLlew requested changes

2021-11-01 16:13 UTC, daiLlew commented on interceptor/interceptor_test.go
> +		b, _ := ioutil.ReadAll(resp.Body)
For completeness you should check this error is also nil - `So(err, ShouldBeNil)`.

2021-11-01 16:32 UTC, redhug1 commented on interceptor/interceptor.go
> +
Here, i'm checking the type of the object - is it 'possibly' json or is if 'possibly' a map thing, and what you propose will validate the json for a second time.
So, no reinvention happening.

2021-11-01 16:34 UTC, redhug1 commented on interceptor/interceptor.go
> +			if bodyLength > 30 {
Well, 30 seems like a reasonable amount of characters to report for anyone who might need to investigate.
Why add yet another line of code defining some constant that will not be used anywhere else ?

2021-11-01 16:39 UTC, redhug1 commented on interceptor/interceptor_test.go
> +		b, _ := ioutil.ReadAll(resp.Body)
Ah, the joys of copy pasta ...
Fixed.

2021-11-02 08:53 UTC, daiLlew commented on interceptor/interceptor.go
> +
Thanks for clearing that up.

I appreciate I'm not fully up to speed to the specific details of this issue so this might be a stupid suggest or something thats already been considered but...

If you're looking to prevent non JSON request bodies being marshalled perhaps using the [HTTP Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) request header would be more appropriate? There is a comprehensive [list of valid media types ](https://www.iana.org/assignments/media-types/media-types.xhtml)which should cover all situations we might face. 

We should be setting this header on all requests, if we're not then I would argue the client is not abiding by HTTP standards.  Using this header will enable us to determine the content type of each request without having to read the body which would be more efficient, it also allows to reject requests requesting invalid/unsupported content types.

2021-11-02 08:54 UTC, daiLlew commented on interceptor/interceptor.go
> +			if bodyLength > 30 {
Thats fine, I just wasn't sure if there was a specific reason 30 or like you said if it was a sensible limit.

2021-11-02 11:24 UTC, redhug1 commented on interceptor/interceptor.go
> +
thanks, will investigate / add.

2021-11-02 11:58 UTC, daiLlew approved these changes

2021-11-02 12:12 UTC, merged