Feature/auth reinstate allow logging
ONSdigital/dp-api-router pull request #170
Opened 2022-08-11 10:48 UTC by AWitcherONS

### What

Add User id to audit log and use permissions api if jwttoken

### How to review
Code complies with current standards 
Test login into Florence for both current auth and new secauth 

### Who can review

anyone but me

2022-08-24 09:57 UTC, nshumoogum requested changes

2022-08-24 09:57 UTC, nshumoogum commented on middleware/audit_test.go
> +
No need to create whitespace here :)

2022-08-24 11:19 UTC, gedge commented on middleware/audit.go
> +		cfg, err := config.Get()
I don't agree

1. the env vars do not change after the app has started (not even sure if that's possible, unless _the app changes them_)
2. the `config.Get()` in the above retrieves the _existing_ config state, see [this line](https://github.com/ONSdigital/dp-api-router/blob/develop/config/config.go#L90), and does not re-read any env vars, anyway

2022-09-12 15:31 UTC, nshumoogum submitted a review, later dismissed

2022-09-12 15:31 UTC, nshumoogum commented on middleware/audit.go
> +		bearerPrefix := "Bearer "
Suggest making bearerPrefix a global constant?

2022-09-22 16:20 UTC, joegasewicz approved these changes

2022-09-22 16:22 UTC, merged