WIP: Enable and fix linting
ONSdigital/dp-api-router pull request #171
Opened 2022-08-11 22:22 UTC by rahulPalliyalil

### What

Describe what you have changed and why.

### How to review

Describe the steps required to test the changes.

### Who can review

Describe who worked on the changes, so that other people can review.

2022-08-12 08:10 UTC, nshumoogum requested changes

2022-08-12 08:10 UTC, nshumoogum commented on interceptor/interceptor.go
> -func shallIgnore(path string) bool {
I don't believe this should be removed

2022-08-12 08:11 UTC, rahulPalliyalil commented on interceptor/interceptor.go
> -func shallIgnore(path string) bool {
this is not being used and the linter complained as well ?

2022-08-12 08:40 UTC, nshumoogum commented on interceptor/interceptor.go
> -func shallIgnore(path string) bool {
I will double check outside of this PR but found this https://github.com/ONSdigital/dp-api-router/pull/171/files

2022-08-12 08:43 UTC, rahulPalliyalil commented on interceptor/interceptor.go
> -func shallIgnore(path string) bool {
sorry didn't understand, the link you send is to my pr right ? btw this is an un exported function so can't be used outside the package and we don't have consumers for it in the package. As i mentioned the linter complained that to be unused as well.

2022-08-15 12:11 UTC, nshumoogum commented on interceptor/interceptor.go
> -func shallIgnore(path string) bool {
Sorry it was this line: https://github.com/ONSdigital/dp-api-router/pull/171/files#:~:text=if%20shallIgnore(r.URL.Path)%20%7B

2022-08-15 12:30 UTC, nshumoogum approved these changes

2022-08-21 20:34 UTC, merged