Allow audit to be disabled for Zebedee routes
ONSdigital/dp-api-router pull request #88
Opened 2020-10-22 15:03 UTC by CarlHembrough

### What
- Allow audit to be disabled for Zebedee routes
We do not explicitly define the Zebedee routes in the router. Zebedee is used as a fallback route, using the `NotFoundHandler`. A Zebedee request is identified by the fact that no other routes would be matched. This solution feels very hacky, but I couldn't think of a better way of doing it. I considered pulling the audit middleware out of the middleware chain and wrapping it around all of the endpoints apart from Zebedee, but this seemed more unsafe as new routes would need to remember the audit wrapper.

### How to review
Review changes / check tests

### Who can review
Anyone

2020-10-27 15:29 UTC, nshumoogum requested changes

2020-10-27 15:29 UTC, nshumoogum commented on middleware/audit_test.go
> +			Convey("Then status Forbidden and expected body is returned", func(c C) {
Test description doesn't seem right

2020-10-29 07:38 UTC, CarlHembrough commented on middleware/audit_test.go
> -	// errCopy                = errors.New("io.Copy error")
I removed it as it is unused.

2020-10-29 07:42 UTC, CarlHembrough commented on middleware/audit_test.go
> +			Convey("Then status Forbidden and expected body is returned", func(c C) {
Good spot - I have updated the description 👍

2020-10-29 08:49 UTC, nshumoogum approved these changes

2020-11-05 15:05 UTC, merged