Feature/job priority
ONSdigital/dp-api-router pull request #97
Opened 2021-01-14 17:51 UTC by mwnicks

### What

Removed count attribute.
Added the priority attribute with the highest value to ensure the service is run on the box.

### How to review

Check there are no 'count' attributes in the nomad config
Check the 'priority' attribute is set to 100 (the max allowed value)

### Who can review

Anyone but me

2021-01-14 18:12 UTC, janderson2 approved these changes

2021-01-15 07:56 UTC, gedge requested changes
please move the `meta` section out of `service` so that the plan parses in `dp-deployer`

2021-01-15 14:30 UTC, gedge approved these changes

2021-01-15 17:39 UTC, mwnicks commented
@janderson2 beat me to the rebase

2021-01-18 09:07 UTC, merged